# Generated by Django 6.0.4 on 2026-05-05 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_prescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='consultation_status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('consulted', 'Consulted'), ('no-show', 'No Show')], default='upcoming', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='refund_admin_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='refund_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='refund_processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='refund_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='refund_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='refund_status',
            field=models.CharField(choices=[('none', 'No Refund'), ('requested', 'Refund Requested'), ('approved', 'Refund Approved'), ('rejected', 'Refund Rejected'), ('completed', 'Refund Completed')], default='none', max_length=20),
        ),
    ]
